version: '3.8'

services:
  # Django application with PyArrow
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - clickhouse
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/backend_db
      - REDIS_URL=redis://redis:6379/0
      - CLICKHOUSE_HOST=clickhouse
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery worker
  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - clickhouse
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/backend_db
      - REDIS_URL=redis://redis:6379/0
      - CLICKHOUSE_HOST=clickhouse
    command: celery -A backend worker --loglevel=info

  # PostgreSQL database
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # ClickHouse for analytics
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  # MinIO for object storage
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9002"

volumes:
  postgres_data:
  clickhouse_data:
  minio_data:
