version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: dw_postgres
    restart: always
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dw_redis
    restart: always
    ports:
      - "6379:6379"

  clickhouse:
    image: yandex/clickhouse-server:21.8
    container_name: dw_clickhouse
    restart: always
    ports:
      - "8123:8123" # HTTP interface
      - "9009:9009" # TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  minio:
    image: minio/minio
    container_name: dw_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console web
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  clickhouse_data:
  minio_data:
