# Generated by Django 4.2.24 on 2025-09-24 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("properties", models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name="UserEvent",
        ),
    ]
